#!/usr/bin/bash

function runATest () {

    fileToUse=$1
    expected=$2
    
    echo ""
    
    out=$(./gDSCodeGen $fileToUse)

    if [ "$out" == "$expected" ]; then
    
        echo "Testing with $fileToUse.dd ... Success: $out"

    else    
    
        echo "Testing with $fileToUse.dd ... Failure"

        echo "Expected: \"$expected\""
        echo "Received: \"$out\""
    
        echo "Failure!!!"
        echo "Failure!!!"
        echo "Failure!!!"

        exit
    fi

}

runATest test_A00 "Successfully wrote file test_A00.py"

echo "Diff the output with the gold file..."
echo "diff test_A00.py test_A00.py_gold"
diff test_A00.py test_A00.py_gold

runATest test_A01 "Keyword 'defineColumnx' not in vocabulary at line 15 in the input file"

runATest test_B01 "'defineTable' found before previous table 'gCounty' ended at line 12 in the input file"
runATest test_B02 "'endTable' found before 'defineTable' at line 9 in the input file"
runATest test_B03 "Missing 'endTable' for table 'gAnimal' at line 26 in the input file"
runATest test_B04 "'defineList', 'defineDict' or 'defineUnary' found inside table definition at line 8 in the input file"
runATest test_B05 "Found 'defineIndex' with no locker specified at line 8 in the input file"

runATest test_C01 "'defineTable' defines a duplicate table name 'gFarm' at line 21 in the input file"
runATest test_C02 "'Index column must be in format '<table>_<table>_Index' at line 22 in the input file"
runATest test_C03 "'Index column refers to a non-existant table at line 22 in the input file"

runATest test_D01 "'defineColumn/Index' element name doesn't start with table name at line 14 in the input file"
runATest test_D02 "'defineIndex' element name isn't '<table>_Name2Index' at line 8 in the input file"

runATest test_E01 "Table 'gFarm' doesn't have a Name column at line 17 in the input file"

runATest test_F01 "Table 'gFarm' HAS A lock routine and DOESN'T HAVE a RowStatus column last at line 17 in the input file"
runATest test_F02 "Table 'gFarm' HAS A lock routine and DOESN'T HAVE a RowStatus column last at line 17 in the input file"
runATest test_F03 "Table 'gFarm' HAS NO lock routine and HAS A RowStatus column at line 17 in the input file"

runATest test_G01 "'defineList/Dict' can not have an initial value at line 6 in the input file"
