#!/usr/bin/python3.9

#
# gDS code generator - See the README.
#

import os
import sys
import inspect

LinesToProcess = []                                         # The input file text, line by line
GeneratedCode = ""                                          # The output file text
 
# Return the currently executing line number (for debug) or comment out
def codeLine():
    return ("")
    #return (f"{inspect.currentframe().f_back.f_lineno}: ")

#
# The code below processes the ".dd" files in multiple passes. The goal here is that each pass completes a simple
# check of the ".dd" file's syntax or semantics.
#

#
# Find, process a bit and return the next non-comment line of input text starting at the given line.
#
def getNextLineToProcess(lineIndex):

    primaryKeyword = None
    optionalArg = [None, None, None]

    while (primaryKeyword is None) and (lineIndex < len(LinesToProcess)):
    
        # Get next line
        line = LinesToProcess[lineIndex]
    
        # Split off any comment
        if "#" in line:
            (line, dummy) = line.split("#", 1)
            
        # If something left
        if line != "":
            
            # Split what's left by whitespace
            optionalArg = line.split()
            
            #print (optionalArg)
            
            # Add possible missing trailing optional args
            optionalArg += [None, None, None]
            
            # Get primaryKeyword for caller to use
            primaryKeyword = optionalArg[0]

        # Bump line pointer
        lineIndex += 1
        
    # Note - trailing optionalArgs are the Python None value only if NO text was specified so, if "None" (no quotes)
    # was specified the string "None" (no quotes) will be returned!!
    return (lineIndex, primaryKeyword, optionalArg[1], optionalArg[2])
    

#
# Verify keywords belong to the proper set of keywords. (Test set "A")
#
def verifyKeywords():

    lineIndex = 0

    while lineIndex < len(LinesToProcess):
    
        (lineIndex, primaryKeyword, elementName, arg1) = getNextLineToProcess(lineIndex)

        if primaryKeyword is not None:
        
            if primaryKeyword not in ("defineTable",
                                      "endTable",
                                      "defineColumn",
                                      "defineIndex",
                                      "defineUnary",
                                      "defineList",
                                      "defineDict"):
                print (f"{codeLine()}Keyword '{primaryKeyword}' not in vocabulary at line {lineIndex} in the input file")
                exit (1)


#
# Next verify the defineTable/endTable keywords match up correctly (Test set "B")
#
def verifyBeginEndConsistency():
    
    lineIndex = 0
    currentTableName = None
    
    indexSeen = False
    lockerName = None

    while lineIndex < len(LinesToProcess):
    
        (lineIndex, primaryKeyword, elementName, arg1) = getNextLineToProcess(lineIndex)
        
        if primaryKeyword is not None:
        
            if primaryKeyword == "defineTable":
                # If out of sequence
                if currentTableName is not None:
                    print (f"{codeLine()}'defineTable' found before previous table '{currentTableName}' ended at line {lineIndex} in the input file")
                    exit (1)
                    
                # Set up to handle a new table definition
                currentTableName = elementName
                lockerName = arg1
                
            elif primaryKeyword == "endTable":
                if currentTableName is None:
                    print (f"{codeLine()}'endTable' found before 'defineTable' at line {lineIndex} in the input file")
                    exit (1)

                # Wipe out table definition
                currentTableName = None
                
            elif primaryKeyword == "defineIndex":
                if lockerName is None:
                    print (f"{codeLine()}Found 'defineIndex' with no locker specified at line {lineIndex} in the input file")
                    exit (1)

            elif primaryKeyword in ("defineList", "defineDict", "defineUnary"):
                if currentTableName is not None:
                    print (f"{codeLine()}'defineList', 'defineDict' or 'defineUnary' found inside table definition at line {lineIndex} in the input file")
                    exit (1)
                
    if currentTableName is not None:
        print (f"{codeLine()}Missing 'endTable' for table '{currentTableName}' at line {lineIndex} in the input file")
        exit (1)
            

#
# Verify the table names do not duplicate. Also ensure table refs make sense. (Test set C)
#
def verifyNoDuplicateTableNamesOrBadRefs():

    lineIndex = 0
    uniqueTableNames = []

    while lineIndex < len(LinesToProcess):
    
        (lineIndex, primaryKeyword, elementName, arg1) = getNextLineToProcess(lineIndex)

        if primaryKeyword is not None:
        
            if primaryKeyword in ("defineTable", "defineUnary", "defineList", "defineDict"):
                if elementName in uniqueTableNames:
                    print (f"{codeLine()}Duplicate element name '{elementName}' defined at line {lineIndex} in the input file")
                    exit (1)
                else:
                    uniqueTableNames.append(elementName)

    lineIndex = 0

    while lineIndex < len(LinesToProcess):
    
        (lineIndex, primaryKeyword, elementName, arg1) = getNextLineToProcess(lineIndex)

        if primaryKeyword is not None:
        
            if primaryKeyword == "defineColumn":
                if elementName.endswith("_Index"):
                    if elementName.count("_") != 2:
                        print (f"{codeLine()}'Index column must be in format '<table>_<table>_Index' at line {lineIndex} in the input file")
                        exit (1)
                    else:
                        (dummy, tableName, dummy) = elementName.split("_")
                        if tableName not in uniqueTableNames:
                            print (f"{codeLine()}'Index column refers to a non-existant table at line {lineIndex} in the input file")
                            exit (1)

#
# Next verify everything between defineTable and endTable starts with the table name.
# Also verify index name is only allowed. (Test set D)
#
def verifyAllStartWithSameTableName():

    lineIndex = 0
    currentTableName = None

    while lineIndex < len(LinesToProcess):
    
        (lineIndex, primaryKeyword, elementName, arg1) = getNextLineToProcess(lineIndex)
        
        if primaryKeyword is not None:
        
            if primaryKeyword == "defineTable":
            
                currentTableName = elementName
                
            elif primaryKeyword in ("defineColumn", "defineIndex"):
            
                if not elementName.startswith(f"{currentTableName}_"):
                    print (f"{codeLine()}'defineColumn/Index' element name doesn't start with table name at line {lineIndex} in the input file")
                    exit (1)
                    
                if (primaryKeyword == "defineIndex") and (elementName != f"{currentTableName}_Name2Index"):
                    print (f"{codeLine()}'defineIndex' element name isn't '<table>_Name2Index' at line {lineIndex} in the input file")
                    exit (1)
                    
                    
            elif primaryKeyword == "endTable":
            
                currentTableName = None


#
# Verify everything has a Name column somewhere. (Test set E)
#
def verifyNameColumnExists():

    lineIndex = 0
    currentTableName = None

    while lineIndex < len(LinesToProcess):
    
        (lineIndex, primaryKeyword, elementName, arg1) = getNextLineToProcess(lineIndex)
        
        if primaryKeyword is not None:
        
            if primaryKeyword == "defineTable":
            
                currentTableName = elementName
                nameSeen = False
                
            elif primaryKeyword == "defineColumn":
            
                if elementName == f"{currentTableName}_Name":
                    nameSeen = True
                    
            elif primaryKeyword == "endTable":
            
                if not nameSeen:
                    print (f"{codeLine()}Table '{currentTableName}' doesn't have a Name column at line {lineIndex} in the input file")
                    exit (1)
                
                currentTableName = None


#
# Verify RowStatus column is last if a lock routine is used. (Test set F)
#
def verifyRowStatusColumnIsLast():

    lineIndex = 0
    currentTableName = None

    while lineIndex < len(LinesToProcess):
    
        (lineIndex, primaryKeyword, elementName, arg1) = getNextLineToProcess(lineIndex)
        
        if primaryKeyword is not None:
        
            if primaryKeyword == "defineTable":
            
                currentTableName = elementName
                
                rowStatusSeen = False
                lastColumn = False
                
                hasLockRoutine = False
                if arg1 is not None:
                    hasLockRoutine = True
                    
            elif primaryKeyword == "defineColumn":
            
                lastColumn = False
            
                if elementName == f"{currentTableName}_RowStatus":
                    rowStatusSeen = True
                    lastColumn = True
                    
            elif primaryKeyword == "endTable":
            
                #print (f"hasLockRoutine, rowStatusSeen, lastColumn = {hasLockRoutine}, {rowStatusSeen}, {lastColumn}")
            
                if hasLockRoutine:
                    if not (rowStatusSeen and lastColumn):
                        print (f"{codeLine()}Table '{currentTableName}' HAS A lock routine and DOESN'T HAVE a RowStatus column last at line {lineIndex} in the input file")
                        exit (1)
                else:
                    if rowStatusSeen:
                        print (f"{codeLine()}Table '{currentTableName}' HAS NO lock routine and HAS A RowStatus column at line {lineIndex} in the input file")
                        exit (1)
                
                currentTableName = None


#
# Generate the code that defines *all* the global shared variables (Test set G)
#
def generateVariableDefinitions():

    global GeneratedCode

    lineIndex = 0
    currentTableName = None

    # Create start of import file.
    
    GeneratedCode += f"# To consume this file (once only) in a Python program: \n"
    GeneratedCode += f" \n"
    GeneratedCode += f"#     from past.builtins import execfile \n"
    GeneratedCode += f"#     execfile ('{sys.argv[1]}.py') \n"
    GeneratedCode += f" \n"
    GeneratedCode += f"# Start of gDS include file ...\n"
    GeneratedCode += f" \n"
    GeneratedCode += f"from multiprocessing import Manager \n"
    GeneratedCode += f"gDSMgr = Manager() \n"

    # Define all the variables needed. Initialize "defineUnary" ones.
    while lineIndex < len(LinesToProcess):
    
        (lineIndex, primaryKeyword, elementName, var1) = getNextLineToProcess(lineIndex)

        if primaryKeyword is not None:
        
            initialValue = var1
            
            if primaryKeyword in ("defineList", "defineDict"):
                if initialValue is not None:
                    print (f"{codeLine()}'defineList/Dict' can not have an initial value at line {lineIndex} in the input file")
                    exit (1)
        
            if primaryKeyword == "defineTable":
                currentTableName = elementName
                GeneratedCode += f" \n"
                GeneratedCode += f"# \n"
                GeneratedCode += f"# Define global shared variables for table {currentTableName} \n"
                GeneratedCode += f"# \n"
                
            elif primaryKeyword == "defineColumn":
                GeneratedCode += f"{elementName} = gDSMgr.list() \n"
                
            elif primaryKeyword == "defineUnary":
                GeneratedCode += f" \n"
                GeneratedCode += f"{elementName} = gDSMgr.list() \n"
                GeneratedCode += f"{elementName}.append({initialValue}) \n"
                
            elif primaryKeyword == "defineIndex":
                GeneratedCode += f"{elementName} = gDSMgr.dict() \n"
                
            elif primaryKeyword == "defineList":
                GeneratedCode += f"{elementName} = gDSMgr.list() \n"
                
            elif primaryKeyword == "defineDict":
                GeneratedCode += f"{elementName} = gDSMgr.dict() \n"
                
            elif primaryKeyword == "endTable":
                currentTableName = None

#
# Generate code to create a row with the initial values presented in the column definitions
#
def generateRowAddCode():

    global GeneratedCode
    
    # The functions below walk through one table's worth of columns doing various things.
    
    # Walk the input lines to the endTable making dummy args
    def addRequiredArgs(lineIndex2):
    
        global GeneratedCode
        
        primaryKeyword = ""
        
        while primaryKeyword != "endTable":
            (lineIndex2, primaryKeyword, elementName, var1) = getNextLineToProcess(lineIndex2)
            if primaryKeyword == "defineColumn":

                # Only generate required dummy args hene
                if var1 is None:
                    (dummy, columnArgName) = elementName.split("_", 1)
                    GeneratedCode += f"    _{columnArgName},\\\n"

        return

    def addOptionalArgs(lineIndex2):
    
        global GeneratedCode
        
        primaryKeyword = ""
        
        while primaryKeyword != "endTable":
            (lineIndex2, primaryKeyword, elementName, var1) = getNextLineToProcess(lineIndex2)
            if primaryKeyword == "defineColumn":

                # Only generate required dummy args here
                if var1 is not None:
                    (dummy, columnArgName) = elementName.split("_", 1)
                    GeneratedCode += f"    _{columnArgName} = {var1},\\\n"

        return

    lineIndex = 0
    currentTableName = None
    currentLockerName = None
    
    while lineIndex < len(LinesToProcess):
    
        (lineIndex, primaryKeyword, elementName, var1) = getNextLineToProcess(lineIndex)
        
        if primaryKeyword is not None:
        
            if primaryKeyword == "defineTable":
            
                currentTableName = elementName
                currentLockerName = var1
                lastColumnName = None
                indexSeen = False
                
                # Generate header based on having a locker ot not
                if currentLockerName is not None:
                
                    GeneratedCode += f"\n"
                    GeneratedCode += f"# \n"
                    GeneratedCode += f"# Add a row to table {elementName} (using locker = {currentLockerName}) \n"
                    GeneratedCode += f"# \n"
                    GeneratedCode += f"def {currentTableName}_AddARowUnderLock(\\\n"
                    
                else:
                    
                    GeneratedCode += f"\n"
                    GeneratedCode += f"# \n"
                    GeneratedCode += f"# Add a row to table {elementName} WITHOUT a lock \n"
                    GeneratedCode += f"# \n"
                    GeneratedCode += f"def {currentTableName}_AddARow(\\\n"
                    
                # Generate input arguments
                addRequiredArgs(lineIndex)
                addOptionalArgs(lineIndex)

                GeneratedCode += f"): \n"
                
                # Lock if there is one
                if currentLockerName is not None:
                    GeneratedCode += f"    {currentLockerName}('lock') \n"
                
            # Now create the row based on the input arguments
            elif primaryKeyword == "defineColumn":
                (dummy, columnArgName) = elementName.split("_", 1)
                GeneratedCode += f"    {elementName}.append(_{columnArgName}) \n"
                lastColumnName = elementName
                
            elif primaryKeyword == "defineIndex":
                indexSeen = True
                
            elif primaryKeyword == "endTable":
            
                # Get current length (index to this entry) *before* unlocking!!
                GeneratedCode += f"    thisIndex = len({lastColumnName}) - 1 \n"
            
                # If using an index check it and set it
                if indexSeen:
                    GeneratedCode += f"    if _Name in {currentTableName}_Name2Index: \n"
                    GeneratedCode += f"        print ('Name value = ', _Name) \n"
                    GeneratedCode += f"        x = 1/0 # Dup row added (Name above) in table {currentTableName} \n"
                    GeneratedCode += f"    {currentTableName}_Name2Index[_Name] = thisIndex \n"
                    GeneratedCode += f"\n"

                if currentLockerName is not None:
                    GeneratedCode += f"    {currentLockerName}('unlock') \n"
                    
                GeneratedCode += f"    return (thisIndex) \n"
                
                currentTableName = None
                currentLockerName = None
                

#
# Generate code to delete all rows in a table where RowStatus is None.
# This is really ugly because doing: "<list> = ..." "de-globals" the list if it's a global list.
#
def generateCompressTableCode():

    global GeneratedCode
    
    # Look for 'defineIndex' to start
    def defineIndexIsInDefinition(lineIndex2):
    
        primaryKeyword = ""
        
        while primaryKeyword != "endTable":
        
            (lineIndex2, primaryKeyword, elementName, var1) = getNextLineToProcess(lineIndex2)
            
            if primaryKeyword == "defineIndex":
            
                return (True)
                
        return (False)

    # Add the creation of the local temp arrays to the compressor code
    def addTempArrays(lineIndex2):
    
        global GeneratedCode
        
        primaryKeyword = ""
        
        while primaryKeyword != "endTable":
            (lineIndex2, primaryKeyword, elementName, var1) = getNextLineToProcess(lineIndex2)
            if primaryKeyword == "defineColumn":

                (dummy, columnName) = elementName.split("_", 1)
                # Create temporary local columns
                GeneratedCode += f"    _{columnName} = [] \n"
            
        return

    # Add code to copy 1 row's column to the temp array
    def addCopyCode(lineIndex2):
    
        global GeneratedCode
        
        primaryKeyword = ""
        
        while primaryKeyword != "endTable":
            (lineIndex2, primaryKeyword, elementName, var1) = getNextLineToProcess(lineIndex2)
            if primaryKeyword == "defineColumn":

                (dummy, columnName) = elementName.split("_", 1)
                # Copy undeleted columns over to the temporary columns
                GeneratedCode += f"            _{columnName}.append({elementName}[tableIndex]) \n"
                
        return

    # Add code to delete the data in the gDS lists (only way it works)!
    def addDeletegDSDataCode(lineIndex2):
    
        global GeneratedCode
        
        primaryKeyword = ""
        
        while primaryKeyword != "endTable":
        
            (lineIndex2, primaryKeyword, elementName, var1) = getNextLineToProcess(lineIndex2)
            
            if primaryKeyword == "defineColumn":

                # Delete all entries in existing gDSMgr lists (the only way to do this job I'm afraid)
                GeneratedCode += f"    del {elementName}[:] \n"
                
        return

    # Add code to copy 1 row's column from the temp arrays back to the global arrays
    def addCopyBackCode(lineIndex2):
    
        global GeneratedCode
        
        primaryKeyword = ""
        
        while primaryKeyword != "endTable":
        
            (lineIndex2, primaryKeyword, elementName, var1) = getNextLineToProcess(lineIndex2)
            
            if primaryKeyword == "defineColumn":

                # Copy over each column element
                (dummy, columnName) = elementName.split("_", 1)
                GeneratedCode += f"        {elementName}.append(_{columnName}[tableIndex]) \n"
                
        return

    lineIndex = 0

    currentTableName = None
    currentLockerName = None
    
    while lineIndex < len(LinesToProcess):
    
        (lineIndex, primaryKeyword, elementName, var1) = getNextLineToProcess(lineIndex)
        
        if primaryKeyword is not None:
        
            if primaryKeyword == "defineTable":
            
                indexSeen = False
            
                currentLockerName = var1
                
                # If there could be an index
                if currentLockerName is not None:

                    # Let's find out for sure
                    indexSeen = defineIndexIsInDefinition(lineIndex)
            
                    currentTableName = elementName
                    
                    GeneratedCode += f"\n"
                    GeneratedCode += f"# \n"
                    GeneratedCode += f"# Delete erased rows in table {elementName} (using locker = {currentLockerName}) \n"
                    GeneratedCode += f"# Note - this procedure must be written as is because of Python/multiprocessing issues! \n"
                    GeneratedCode += f"# \n"
                    GeneratedCode += f"def {currentTableName}_CompressTableUnderLock(): \n"
                    GeneratedCode += f"\n"
                    GeneratedCode += f"    {currentLockerName}('lock') \n"
                    GeneratedCode += f"\n"
                            
                    # Add temp lists, 1/table column
                    addTempArrays(lineIndex)

                    GeneratedCode += f"\n"
                    GeneratedCode += f"    for tableIndex in range(len({currentTableName}_RowStatus)): \n"
                    GeneratedCode += f"        if {currentTableName}_RowStatus[tableIndex] is not None: \n"
                    
                    # Add code to copy the data over if the row's not been not erased
                    addCopyCode(lineIndex)

                    # If an index, pare it down by one
                    if indexSeen:
                        GeneratedCode += f"        else: \n"
                        GeneratedCode += f"            del {currentTableName}_Name2Index[{currentTableName}_Name[tableIndex]] \n"
                    
                    GeneratedCode += f"\n"
                    
                    # Delete all the gDS columns in the table using a "del"
                    addDeletegDSDataCode(lineIndex)
                    
                    # Get ready to copy the data back to the gDS columns
                    GeneratedCode += f"\n"
                    GeneratedCode += f"    for tableIndex in range(len(_RowStatus)): \n"
                    
                    # And add code to copy temp arrays back to global columns
                    addCopyBackCode(lineIndex)

                    if indexSeen:
                
                        # Update entries that remain in the index
                        GeneratedCode += f"\n"
                        GeneratedCode += f"    for tableIndex in range(len({currentTableName}_RowStatus)): \n"
                        GeneratedCode += f"        {currentTableName}_Name2Index[{currentTableName}_Name[tableIndex]] = tableIndex \n"

                    GeneratedCode += f"\n"
                    GeneratedCode += f"    {currentLockerName}('unlock') \n"
                    GeneratedCode += f"\n"
                    GeneratedCode += f"    return \n"

            # Skip here because we did everything above
            elif primaryKeyword == "defineColumn":
                pass

            elif primaryKeyword == "defineIndex":
                pass
                
            elif primaryKeyword == "endTable":
                pass
            
#
# Generate code to print out the rows in each table for debug
#
def generateTableDumpCode():

    global GeneratedCode

    lineIndex = 0
    currentTableName = None
    currentLockerName = None
    
    while lineIndex < len(LinesToProcess):
    
        (lineIndex, primaryKeyword, elementName, arg1) = getNextLineToProcess(lineIndex)
        
        if primaryKeyword is not None:
        
            if primaryKeyword == "defineTable":

                currentTableName = elementName
                currentLockerName = arg1

                GeneratedCode += f"\n"
                GeneratedCode += f"# \n"
                GeneratedCode += f"# Print values out for table '{currentTableName}' (using locker = {currentLockerName}) \n"
                GeneratedCode += f"# \n"
                GeneratedCode += f"def {currentTableName}_DumpTable(rangeListToDump = None): \n"
                
                headerGenerated = False
                
            elif primaryKeyword == "defineColumn":
                # If dumping the first column of the table generate a header with information about the table
                if not headerGenerated:
                    headerGenerated = True
                    if currentLockerName is not None:
                        GeneratedCode += "\n"
                        GeneratedCode += f"    {currentLockerName}('lock') \n"
                    GeneratedCode += "\n"
                    GeneratedCode += f"    print (f'**************') \n"
                    GeneratedCode += f"    print (f'**************') \n"
                    GeneratedCode += f"    print ('    Table %24s (using locker = {currentLockerName}) has %d entries' % ('{currentTableName}', len({currentTableName}_Name))) \n"
                    GeneratedCode += f"    print (f'**************') \n"
                    GeneratedCode += f"    print (f'**************') \n"
                    GeneratedCode += f"    print (f'') \n"
                    GeneratedCode += "\n"
                    GeneratedCode += f"    for i in range (0, len({currentTableName}_Name)): \n"
                    GeneratedCode += f"        if (rangeListToDump is None) or (i in rangeListToDump): \n"
                    GeneratedCode += f"            print ('    Row index = %d' % (i)) \n"
                    
                # If an index to another table
                if elementName.endswith("_Index"):
                    # Fail here if the index isn't of the proper form
                    (dummy, nextTableName, dummy) = elementName.split("_", 2)
                    GeneratedCode += f"            print ('    %30s = %10s  (%30s)' % ('{elementName}', {elementName}[i], {nextTableName}_Name[{elementName}[i]])) \n"
                    
                else:
                    GeneratedCode += f"            print ('    %30s = %10s' % ('{elementName}', {elementName}[i])) \n"
                    
            elif primaryKeyword == "defineIndex":
                pass
                
            elif primaryKeyword == "endTable":
                if currentLockerName is not None:
                    GeneratedCode += "\n"
                    GeneratedCode += f"    {currentLockerName}('unlock') \n"
                GeneratedCode += "\n"
                GeneratedCode += f"    return \n"
                currentTableName = None
                currentLockerName = None
            

###################################
###
### Main
###
###################################

# Get the datastore definition file name prefix
datastoreNamePrefix = sys.argv[1]
if not os.path.exists(datastoreNamePrefix + ".dd"):
    print (f"{codeLine()}File {datastoreNamePrefix + '.dd'} does not exist")
    exit (1)

# Read in the entire datastore definition file
LinesToProcess = open(datastoreNamePrefix + ".dd", "r").read().splitlines()

# The functions below zip through the .dd file over and over. This is done by design. This is not a compiler; the goal 
# being that is *should* be more maintainable than a compiler.

# (Test set A) Verify all keywords are in our vocabulary
verifyKeywords()

# (Test set B) Verify the table definition start/end/index keywords match up correctly
verifyBeginEndConsistency()

# (Test set C) Look for duplicate table names and references to non-existent tables
verifyNoDuplicateTableNamesOrBadRefs()

# (Test set D) Verify all table defineColumn / defineIndex citations start with the correct table name
# Also, that defineIndex is inside begin/end blocks
verifyAllStartWithSameTableName()

# (Test set E) All tables need a Name column
verifyNameColumnExists()

# (Test set F) If a table lock is given, the RowStatus column must be there and last
verifyRowStatusColumnIsLast()

# Generate code to declare all global shared lists and dictionaries (some will be used in gDS "tables" and some
# will remain uninitialized with no other semantics)
# (Test set G)
generateVariableDefinitions()

# Generate code to add a table row when called
generateRowAddCode()

# Generate code to compress a table when called
generateCompressTableCode()

# Generate code to print/dump each table's rows when called
generateTableDumpCode()

# Write out the Python file <file name>.py
open(f"{datastoreNamePrefix}.py", "w").write(GeneratedCode)
print (f"Successfully wrote file {datastoreNamePrefix}.py")